---
# note that the version below should match
# what is in the solr.json file
driver:
  name: vagrant
  require_chef_omnibus: 12.7.2

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[nordsolr::default]
    attributes:
