name 'nordsolr'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures nordsolr'
long_description 'Installs/Configures nordsolr'
version '0.1.0'
